sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
  - secure: Wy5TcqGLDIcYADmPCy9bu3czkSJWqLYwD0HynIns6vL9IXimryW023Y5TzrhBQdut5Pr6GGmpwIVUYqQ8N/KhmGrHBwapvntdW4gyeAIDmpLFNiQv30jBtpcbEKh1JZsrTgiOr0Ym7ypAN2caV2f1FXd2DpjJSTkeNk5fau8nDvnAeoEVuh7CChNytSj4Rr0aQd2SqTxccWuF0k7RF6ywJfak6LmFpOLr8GImpz2wPou134TOEofbz2sGiKgOwk79WLMPt8BjpGV6SIicDKZcK7uR8ndHr1xGaaMXLN3JfU1zTRqzdnXZnIWgeNTEtPoeUmj1Jl17sab23ZKgOx2p4J1AWjO/J8Ce2YsOidDMQ7QVEn72KNSfRa+BF/NyRPSGMiHXwIdkdXE1FHeKjPd9BmhpF6w6+xJd6kC/GusjrxErJV0mAisfDVG0kvN9l3/PR/jXV+hAt++deMFieVdTIelJ6pYY4j2I9VGCFms8I4BTJTUzGOU5HzvFez4hdVkYw4oQoNitlKaDaZ4XUjEtHRuUxn+4jNTEeidgdRGjrGN9gErvak0Zk6AucNX4HkX4gcBCti/Ip/7OeqpfHgpwyjA/KQCSn4d/dWIW42Z+cESlnRMFR5ALV8qK0JbL/4+nlHo+y2MUDp7uWFRPK9Y5pDb1xYjAljXBd+M8hW0k+Q=
  - secure: zhXkjJz+vzF7xzPo7KNGmct8FXAiaRQ6HnGnRfr1sQd/FfDL7WovOQD4PFkAHRNzJuhkGSJ3NmfP+gaSv5kvI7C9/tI624bgZfO9NYwfTZNNz9g36RtlCYNcQuwPUG0daIdfFYDRz8GPJ+kiBnEXmAJf5XWeBlMJx/R1x7pipEHQeZY+WyISvLZTnHg8cOfWajmRBNk26vkZ6psmiW/SVekVyIEVTDkrvCeuArpacHLTjURTESCugS1r30ep3P5sFruF7cy358kO5IOdEwBbnuAV9obCqG2DgnrHUMaHTPm6APICTGPqmYGAszC2R5mOMD+vzPsmmNj+RK/FQu9FT9cwIwuzAT+OUHF5svVxpQGiPoX00ZhBgNwvYLZucAKEcWkDGtcF/KNlHLVBiVzPBlSfym/w3X1yy61VXr6kPPr7/AzMgeI4d3Gsx7hRMUVXT6AfTvi45l0w9BivvhzTYngQydaLDLH9ud99vdh6yv1q5KXJIhx6+2u/FKlEpO+0+YaJRjxx7pxL8a0nBJTdY34wqN1+imd3QHB2tZP3zB2ouyd4f3UhYwTJ0ze5OAI0QkSwvn8jME9LHn+Dc8H6ukMYNQ8XX4AFV9mJCVpk5xHagUagrn082bGtLkTPopW257BiJRIE0iplb3/U3fWqRFVntIB9ZQoghOw124SeQCY=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: Tc/buj2bEYRvzzmXUHacOCTher2zvGjACq0gQOfB/8RT+IZhSUdsVM0n9QM3kcXnb7UVVPNT7K5IOzZ0NTBmtIfMM0lBq0ZGJZ9UrJpIrKdRsWckDar2AwECBtOAA+BnNQtgR/aUQBShR6JobvRjcwViacb+O+iJt1YauDQgA8fnIJbJB7SIDaNq6Q9MWKGRX/37NMaT0rBxqB8LyQk7RMFcWWvv5TZ6esAZWjAIkYQWySL4IcxzLtKVihnwgBTUSeIGQ2mXJ8kTebFcnsr40qopf5sCqfIQ1R6Z7qi7blk0sqcoeM7uX5f+onIAX0vZTwtPqcz1X9aoq10YBOIXYWzI3lj/OobxkpRi1qmgecAG/VrfiHV7Aa+9SnjYpj1pLzEF+jyDGDc1dtzwSBWrTZy7eC0Ml8jaWRxdf4dL64naJLsbTH8RMuLjxjdzvANnBM6RrUUYCNZFMwYuB25CxWbNYWq+qNaQMOj/R0pFklvKbddhewFdrGHWO/UYn2Yhpx1XoqwxC42tjI5s/ZXVZvyZoY4Iiwme7mPwqWLBVDsDxPIlttjCZGp9KXUsbtOO5nsyLzdCRbybjSEAK/+HlUVKQbqbCW+27hljjoOfc0z6S9jpp1AFVsx8tkxV6IzTpBYYjh3oOO0h9flL3Gi9cfnSrVruNHgXll5XJzRO+xo=
