name: Package and release
on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Trim changelog
        run: sed -ni '1p;2,/^###/{/^###/q;p;}' CHANGELOG.md

      - name: Package and release
        uses: BigWigsMods/packager@75faeae
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
